name = "toko"
main = "src/index.tsx"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

routes = [
  "toko.obotzone.com/*"
]

[[d1_databases]]
binding = "DB"
database_name = "toko-db"
database_id = "914969ac-63ce-4360-9c9b-093ea2fe45e1"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "toko-images"
